bcgov/jag-efax

.dockerignore
Dockerfile.faxlistener
docker-compose.yml
fax-listener/pom.xml
fax-listener/src/main/java/ca/bc/gov/ag/FaxListenerApplication.java
fax-listener/src/main/resources/application.yaml
fax-listener/src/test/java/ca/bc/gov/ag/ApplicationTest.java
fax-listener/src/test/java/ca/bc/gov/ag/BaseTestSuite.java
fax-listener/src/test/java/ca/bc/gov/ag/redis/TestRedisConfiguration.java
fax-listener/src/test/resources/application.yaml
pom.xml

https://justice.gov.bc.ca/jira/browse/EFAX-24
Stubbed out a simple new project module, fax-listener
- added module to project pom.xml
- added module to docker-compose
Runs on port 8083.
http://localhost:8083/actuator/health
{"status":"UP"}
mvn verify

EFAX-24 created new fax listener module

---

fax-listener/pom.xml
fax-listener/src/main/java/ca/bc/gov/ag/AutoConfiguration.java
fax-listener/src/main/java/ca/bc/gov/ag/fl/config/ExchangeProperties.java
fax-listener/src/main/java/ca/bc/gov/ag/fl/config/ExchangeServiceFactory.java
fax-listener/src/main/java/ca/bc/gov/ag/fl/scheduler/EmailPoller.java
fax-listener/src/main/java/ca/bc/gov/ag/fl/service/EmailService.java
fax-listener/src/main/java/ca/bc/gov/ag/fl/service/EmailServiceImpl.java
fax-listener/src/main/resources/application.yaml
fax-listener/src/test/resources/application.yaml

https://justice.gov.bc.ca/jira/browse/EFAX-24
Stubbed out a simple email service that polls an Exchange server for incoming emails.
TODO: actually do something with the returned results.

Added a scheduler to poll for exhange emails

---

src/main/java/ca/bc/gov/ag/efax/mail/config/ExchangeConfiguration.java
src/main/java/ca/bc/gov/ag/efax/mail/service/EmailServiceImpl.java

Fixed NPE in legacy code.
ran the application and attempted to send an email

EFAX-24, fixed NPE

---

src/main/java/ca/bc/gov/ag/efax/mail/service/parser/EmailParser.java
src/main/java/ca/bc/gov/ag/efax/mail/service/parser/UndeliverableVisitor.java

Small PR to remove potential PI from logs

remove potential PI from logs

---

.github/workflows/code-climate-coverage-aggregation.yml
pom.xml

Code Climate GitHub action

---

README.md

- [EFAX-17] (https://justice.gov.bc.ca/jira/browse/EFAX-17)
- added codeclimate badges

added codeclimate badges to README EFAX-17

---

src/main/java/ca/bc/gov/ag/efax/mail/util/FaxUtils.java
src/test/java/ca/bc/gov/ag/efax/mail/util/FaxUtilsTest.java

Improved the Fax Formatter to match the new faxFormat used in exchange server.
mvn verify

updated fax formatter to match new exchange server req.

---

.github/workflows/code-climate-coverage-aggregation.yml
Dockerfile
src/main/java/ca/bc/gov/ag/efax/mail/config/ExchangeProperties.java
src/main/java/ca/bc/gov/ag/efax/mail/scheduled/EmailPoller.java
src/main/java/ca/bc/gov/ag/efax/mail/service/EmailServiceImpl.java
src/main/java/ca/bc/gov/ag/efax/mail/util/FaxUtils.java
src/main/java/ca/bc/gov/ag/efax/ws/scheduled/ScheduledTasks.java
src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceImpl.java
src/main/resources/application.yaml
src/test/java/ca/bc/gov/ag/efax/ApplicationTest.java
src/test/java/ca/bc/gov/ag/efax/BaseTestSuite.java
src/test/java/ca/bc/gov/ag/efax/redis/TestRedisConfiguration.java
src/test/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceTest.java
src/test/resources/application-test.yaml

https://justice.gov.bc.ca/jira/browse/EFAX-22
- Added an integration test for the DocumentDistributionMainProcess service. This included creating an in-memory redis server and mock implementation of Microsoft's Exchange Server.
- Simplified the scheduled tasks to be loaded into spring context if enabled by using `@ConditionalOnProperty`
All integration tests now run in the same applicationContext.
mvn verify
docker-compose up -d --build, confirmed application still works.

Created document distribution service integration tests

---

pom.xml
src/main/java/ca/bc/gov/ag/efax/mail/scheduled/EmailPoller.java
src/main/java/ca/bc/gov/ag/efax/mail/service/parser/EmailParser.java
src/main/java/ca/bc/gov/ag/efax/mail/service/parser/EmailVisitor.java
src/main/java/ca/bc/gov/ag/efax/mail/service/parser/UndeliverableVisitor.java
src/main/java/ca/bc/gov/ag/efax/mail/util/FaxUtils.java
src/main/java/ca/bc/gov/ag/efax/ws/config/WebServiceConfig.java
src/main/java/ca/bc/gov/ag/efax/ws/endpoint/DocumentDistributionEndpoint.java
src/main/java/ca/bc/gov/ag/efax/ws/exception/DetailSoapFaultDefinitionExceptionResolver.java
src/main/java/ca/bc/gov/ag/efax/ws/exception/ServiceFaultException.java
src/main/java/ca/bc/gov/ag/efax/ws/scheduled/ScheduledTasks.java
src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionService.java
src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceImpl.java
src/test/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceTest.java

Updated generated webservice model package location to be consistent with rest of app
- updated package path in pom.xml
- updated WebServiceConfig to use modified package location
- updated imports of a few files that use the model
mvn verify

updated generated model package to be consistent with rest of app

---

src/main/java/ca/bc/gov/ag/efax/mail/util/FaxUtils.java
src/main/java/ca/bc/gov/ag/efax/ws/endpoint/DocumentDistributionEndpoint.java
src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionService.java
src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceImpl.java
src/test/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceTest.java

Improved JavaDocs in DocumentDistributionService so the service contract is more clear.
mvn verify

improved JavaDocs

---

pom.xml

Fixed the jacoco plugin (code-coverage) to exclude generated code.

fixed jacoco excludes to not consider generated code

---

pom.xml
src/main/java/ca/bc/gov/ag/efax/ws/endpoint/DocumentDistributionEndpoint.java
src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionService.java
src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceImpl.java
src/test/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceTest.java
src/test/resources/application-test.yaml

Added junit tests for the soap webservice.
mvn verify

Added junit tests for the soap webservice

---

src/main/java/ca/bc/gov/ag/efax/mail/service/parser/EmailParser.java
src/main/java/ca/bc/gov/ag/efax/mail/util/DateUtil.java
src/test/java/ca/bc/gov/ag/efax/BaseTestSuite.java
src/test/java/ca/bc/gov/ag/efax/mail/service/parser/EmailParserTest.java
src/test/java/ca/bc/gov/ag/efax/mail/service/parser/UndeliverableVisitorTest.java
src/test/java/ca/bc/gov/ag/efax/mail/util/DateUtilTest.java
src/test/java/ca/bc/gov/ag/efax/ws/endpoint/DocumentDistributionEndpointTest.java
src/test/java/ca/bc/gov/ag/efax/ws/scheduled/ScheduledTasksTest.java
src/test/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceTest.java

Added junit tests for ScheduledTasks and EmailParser
mvn verify

created ScheduledTasksTest

---

src/test/java/ca/bc/gov/ag/efax/mail/service/EmailServiceTest.java

Added junit tests for EmailService that retrieves and deletes emails from exchange.
mvn verify

Added junit tests for EmailService

---

src/main/java/ca/bc/gov/ag/efax/pdf/util/PDFParser.java
src/test/java/ca/bc/gov/ag/efax/BaseTestSuite.java
src/test/java/ca/bc/gov/ag/efax/pdf/service/PdfServiceTest.java
src/test/java/ca/bc/gov/ag/efax/pdf/util/PDFParserTest.java
src/test/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceTest.java

Created PDFParser tests
Created PDFService tests
mvn verify

Created PDFParser tests

---

.github/workflows/dev-efax-service-build.yaml

Create Github Action for build and push Webservice Image

---

pom.xml
src/main/resources/logback-splunk.xml

EFAX-41, added splunk logging to pom.xml

Added logback-splunk.xml

---

.github/helpers/latest_java_version.sh
.github/workflows/dev-efax-service-build.yaml

adding shell script for version

---

.github/workflows/dev-efax-service-build.yaml

adding a where am i block

---

.github/workflows/dev-efax-service-build.yaml

Adding version check

---

.github/workflows/dev-efax-service-build.yaml

Adding Proper Tag

---

.github/workflows/dev-efax-service-build.yaml

Breaking Actions into Components with Version Check

---

.github/helpers/deploy_efax.sh

Adding Deployment Helper Script

---

README.md

Adding Project Lifecycle Badge

---

.github/helpers/deploy_efax.sh
openshift/templates/efax-webservice/dc.yaml

Update Deploy Helper and DC Template

---

.github/helpers/deploy_efax.sh
.github/workflows/dev-efax-service-build.yaml
openshift/templates/efax-webservice/dc.yaml

Deployment Automation to DEV

---

.github/workflows/dev-efax-service-build.yaml

Git Action can't run shell script

---

.github/helpers/deploy_efax.sh
.github/workflows/dev-efax-service-build.yaml

passing arugments to helper file

---

.github/workflows/dev-efax-service-build.yaml

final argument troubleshooting

---

.github/helpers/deploy_efax.sh
.github/workflows/dev-efax-service-build.yaml

remove version argument

---

.github/workflows/dev-efax-service-build.yaml

Environment Variables?

---

.github/helpers/deploy_efax.sh
.github/workflows/dev-efax-service-build.yaml

More Environment Variables

---

.github/helpers/deploy_efax.sh

Echo Troubleshooting

---

.github/workflows/dev-efax-service-build.yaml

troubleshooting

---

.github/helpers/deploy_efax.sh
.github/workflows/dev-efax-service-build.yaml

environment variables

---

openshift/templates/efax-webservice/dc.yaml

Deployment Config Bug

---

.github/helpers/application_health.sh
.github/workflows/dev-efax-service-build-deploy.yaml

Application Deploy Health Check

---

.github/workflows/test-efax-service-build-deploy.yaml

Creating TEST deployment Git Action

---

.github/workflows/dev-efax-service-build-deploy.yaml
.github/workflows/test-efax-service-build-deploy.yaml

Renaming TEST and DEV Git Actions

---

src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceImpl.java
src/main/resources/application.yaml

Enabled JUSTIN callback, improved logging around the callback.
mvn test

enabled Justin callback

---

.github/helpers/trim_java_version.sh

Helper Script to Trim Version

---

.github/workflows/prod-efax-service-build-deploy.yaml

Creating PROD Release Workflow

---

.github/helpers/update_java_version.sh

Update Version Helper Script

---

.github/helpers/deploy_efax.sh
.github/workflows/prod-efax-service-build-deploy.yaml

Argument too long Error troubleshooting

---

pom.xml

Troubleshooting Splunk

---

src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceImpl.java

Supplied an unmarshaller, even though we're not interested in the results from Justin, the service still needs to parse the results.
mvn test

Added unmarshaller

---

src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceImpl.java
src/main/resources/DocumentDistributionMainProcess.wsdl
src/main/resources/DocumentDistributionMainProcess.xsd

JUSTIN callback wsdl was out of date.
- updated wsdl,
- enhanced logging.
mvn test

Fixed JUSTIN callback with updated wsdl

---

src/main/java/ca/bc/gov/ag/efax/mail/service/EmailServiceImpl.java
src/main/java/ca/bc/gov/ag/efax/pdf/service/PdfService.java
src/main/java/ca/bc/gov/ag/efax/pdf/util/PdfUtils.java
src/main/java/ca/bc/gov/ag/efax/ws/endpoint/DocumentDistributionEndpoint.java
src/main/java/ca/bc/gov/ag/efax/ws/scheduled/ScheduledTasks.java
src/main/java/ca/bc/gov/ag/efax/ws/service/DocumentDistributionServiceImpl.java

Some logging statements were promoted from DEBUG to INFO to better capture activity. Using INFO, we should be able to:
- count number of incoming initial requests
- count number of faxes that were successfully flattened
- count number of faxes with an invalid mimetype
- count number of faxes that timed out (no response from exchange on whether the sent fax worked or not)
- count number of outgoing responses back to JUSTIN.
The first and last counts should match.  Counts between are interesting stats.

Adjusted log level of some statements

---

src/main/java/ca/bc/gov/ag/efax/pdf/util/PdfUtils.java

Enhanced logging around PDF retrieval.

Enhanced logging

---

pom.xml
src/test/java/ca/bc/gov/ag/efax/pdf/service/PdfServiceTest.java

bump version to 1.0.0

---

Dockerfile

Change hard coded version

---

Dockerfile
pom.xml

Moving version to 1.1.0-SNAPSHOT

Move to 1.1.0-SNAPSHOT

---

.github/workflows/prod-efax-service-build-deploy.yaml

Removing clause to run prod workflow when an new relase is published

---

.github/workflows/prod-efax-service-build-deploy.yaml

Removing tasks that where used to build and push the docker image

---

Dockerfile
pom.xml

Update pom in preparation for 1.0.1 release to TEST and PROD.

Tag 1.0.1, includes fix for log4j vulnerability

---

Dockerfile

UPdate reference in docker file

Update version in docker file

---

pom.xml

Bumped log4j to 2.17.0, Splunk to 1.11.2, Tagged 1.0.4

Bumped log4j to 2.17.0, Splunk to 1.11.2, Tagged 1.0.4

---

pom.xml

Bump log4j to 2.17.1, splunk to 1.11.4

Bump log4j to 2.17.1, splunk to 1.11.4

---

pom.xml

Bumped version in main to 1.0.6

---

jag-efax/src/test/java/ca/bc/gov/ag/efax/ws/endpoint/DocumentDistributionEndpointTest.java

Fixed hard-coded reference to sample pdf in a junit test.
mvn clean verify

Fixed hard-coded reference to sample pdf

---

jag-efax/src/main/java/ca/bc/gov/ag/efax/pdf/config/PdfConfiguration.java

Update endpoint properties

---

distribution-client-proxy/pom.xml
jag-efax/pom.xml

Bumped version to 1.0.7

---

pom.xml

bumping version to 1.0.7

---

distribution-client-proxy/pom.xml
jag-efax/pom.xml
pom.xml

bumping project to version 1.0.8

---

.mvn/maven.config.bak
distribution-client-proxy/src/main/java/ca/bc/gov/ag/proxy/DocumentDistributionRequestBuilder.java
jag-efax/pom.xml

fix of e-fax page JUSTINCSB-2668

---

.github/workflows/prod-efax-push-deploy.yaml
.github/workflows/test-efax-push-deploy.yaml

new pipelines

---

jag-efax/src/main/resources/application.yaml
jag-efax/src/test/resources/application-test.yaml

fix redis connection exception on OpenShift DEV port

---

.github/workflows/prod-efax-push-deploy.yaml

backup prod image

---

distribution-client-proxy/pom.xml
jag-efax/pom.xml
pom.xml

Update to new dev version

---

.github/workflows/code-climate-coverage-aggregation.yml
.github/workflows/dev-efax-build-push.yaml
.github/workflows/dev-efax-service-build-deploy.yaml
.github/workflows/prod-efax-service-build-deploy.yaml
.github/workflows/test-efax-service-build-deploy.yaml
.github/workflows/trivy-analysis.yml
jag-efax/pom.xml
jag-efax/src/main/java/ca/bc/gov/ag/efax/pdf/config/WebServiceSenderWithAuth.java
jag-efax/src/test/java/ca/bc/gov/ag/efax/ws/scheduled/ScheduledTasksTest.java

update to spring boot 3.4.5
